// polling_divisions.dart

Map<String, List<String>> pollingDivisions = {
  'Colombo': [
    'Colombo Central',
    'Colombo East',
    'Colombo North',
    'Colombo South',
  ],
  'Gampaha': [
    'Gampaha Central',
    'Gampaha North',
    'Gampaha South',
  ],
  'Kalutara': [
    'Kalutara Central',
    'Kalutara North',
    'Kalutara South', 
  ],
  'Kandy': [
    'Kandy Central',
    'Kandy East',
    'Kandy North',
    'Kandy South', 
  ],
  'Matale': [
    'Matale Central',
    'Matale East',
    'Matale North',
    'Matale South', 
  ],
  'Nuwara Eliya': [
    'Nuwara Eliya Central',
    'Nuwara Eliya East',
    'Nuwara Eliya North',
    'Nuwara Eliya South',
  ],
  'Galle': [
    'Galle Central',
    'Galle East',
    'Galle North',
    'Galle South', 
  ],
  'Matara': [
    'Matara Central',
    'Matara East',
    'Matara North',
    'Matara South', 
  ],
  'Hambantota': [
    'Hambantota Central',
    'Hambantota East',
    'Hambantota North',
    'Hambantota South', 
  ],
  'Jaffna': [
    'Jaffna Central',
    'Jaffna East',
    'Jaffna North',
    'Jaffna South', 
  ],
  'Mannar': [
    'Mannar Central',
    'Mannar East',
    'Mannar North',
    'Mannar South', 
  ],
  'Vavuniya': [
    'Vavuniya Central',
    'Vavuniya East',
    'Vavuniya North',
    'Vavuniya South', 
  ],
  'Mullaitivu': [
    'Mullaitivu Central',
    'Mullaitivu East',
    'Mullaitivu North',
    'Mullaitivu South', 
  ],
  'Batticaloa': [
    'Batticaloa Central',
    'Batticaloa East',
    'Batticaloa North',
    'Batticaloa South', 
  ],
  'Ampara': [
    'Ampara Central',
    'Ampara East',
    'Ampara North',
    'Ampara South', 
  ],
  'Trincomalee': [
    'Trincomalee Central',
    'Trincomalee East',
    'Trincomalee North',
    'Trincomalee South', 
  ],
  'Kurunegala': [
    'Kurunegala Central',
    'Kurunegala East',
    'Kurunegala North',
    'Kurunegala South', 
  ],
  'Puttalam': [
    'Puttalam Central',
    'Puttalam East',
    'Puttalam North',
    'Puttalam South', 
  ],
  'Anuradhapura': [
    'Anuradhapura Central',
    'Anuradhapura East',
    'Anuradhapura North',
    'Anuradhapura South', 
  ],
  'Polonnaruwa': [
    'Polonnaruwa Central',
    'Polonnaruwa East',
    'Polonnaruwa North',
    'Polonnaruwa South', 
  ],
  'Badulla': [
    'Badulla Central',
    'Badulla East',
    'Badulla North',
    'Badulla South', 
  ],
  'Monaragala': [
    'Monaragala Central',
    'Monaragala East',
    'Monaragala North',
    'Monaragala South', 
  ],
  'Ratnapura': [
    'Ratnapura Central',
    'Ratnapura East',
    'Ratnapura North',
    'Ratnapura South', 
  ],
  'Kegalle': [
    'Kegalle Central',
    'Kegalle East',
    'Kegalle North',
    'Kegalle South', 
  ],
};
